### ISSUE TITLE
File nametranslation missing

### ISSUE THREAD

**Issue by iwaseasahi** [iwaseasahi/christchurches-map#771]
## 背景

ローカルで rspec を実行すると、以下のエラーが発生します。

```
Failures:

  1) PhotoUploader thumb resize_to_fit
     Failure/Error: photo.save!

     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました: File nametranslation missing: ja.errors.messages.rmagick_processing_error
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:80:in `raise_validation_error'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:53:in `save!'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:302:in `block in save!'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
     # /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:302:in `save!'
     # /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:48:in `save!'
     # ./spec/uploaders/photo_uploader_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ./spec/uploaders/photo_uploader_spec.rb:13:in `open'
     # ./spec/uploaders/photo_uploader_spec.rb:13:in `block (2 levels) in <top (required)>'
```

## 目的

エラー解決

## 完成条件

* 原因を調査すること
* 解決すること

**Comment by iwaseasahi** [comment]
```
root@cc054290dc10:/usr/src/app# convert -version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

**Comment by iwaseasahi** [comment]
macbook 2015 では spec が通りました。
なので、macbook 2020 固有の問題のようです。

**Comment by iwaseasahi** [comment]
imagemagick の version は同じでした。

**Comment by iwaseasahi** [comment]
macbook 2015 の Docker for mac が 3.0.3 だったので、3.6.0 にアップグレードしたら同じエラーが発生しました。

**Comment by iwaseasahi** [comment]
Docker for mac を 4.0.0 に上げても解決できませんでした。

**Comment by iwaseasahi** [comment]
こちらを参考に 3.0.4 に下げてみます。
https://qiita.com/A-Kira/items/8ae66838b019683704d1

**Comment by iwaseasahi** [comment]
https://docs.docker.jp/docker-for-mac/troubleshoot.html

**Comment by iwaseasahi** [comment]
Docker for mac の version を下げることができなかったので、一旦 4.0.0 に上げたままにします。

**Comment by iwaseasahi** [comment]
CI では spec が通るので、ローカルでは無理に解決しません。
close します。
