### ISSUE TITLE
ECS で sidekiq を動かす

### ISSUE THREAD

**Issue by iwaseasahi** [iwaseasahi/christchurches-map#824]
## 背景

https://github.com/iwaseasahi/christchurches-map/issues/782

上記 issue で ECS で動かすようにしました。
ですが、sidekiq が動いていないので、バックグラウンドジョブを処理できていません。

## 目的

バックグラウンドジョブを処理する

## 完成条件

* どのように実現するか調査すること
* 解決すること

**Comment by iwaseasahi** [comment]
元々は以下のコマンドで daemon 化して動かしていました。

```
$ bundle exec sidekiq -C config/sidekiq.yml
```

ですが、sidekiq 6 から daemon 化を止めたとのことです。
止めた理由は以下に記載されています。
https://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/

**Comment by iwaseasahi** [comment]
https://github.com/mperham/sidekiq/wiki/Getting-Started

**Comment by iwaseasahi** [comment]
https://github.com/mperham/sidekiq/wiki/Using-Redis

**Comment by iwaseasahi** [comment]
active job に切り替えることも検討します。
https://railsguides.jp/active_job_basics.html

**Comment by iwaseasahi** [comment]
> production環境でのジョブのキュー登録と実行では、キューイングのバックエンドを用意しておく必要があります。具体的には、Railsで使うべきサードパーティのキューイングライブラリを決める必要があります。 Rails自身が提供するのは、ジョブをメモリに保持するインプロセスのキューイングシステムだけです。 プロセスがクラッシュしたりコンピュータをリセットしたりすると、デフォルトの非同期バックエンドの振る舞いによって主要なジョブが失われてしまいます。アプリケーションが小規模な場合やミッションクリティカルでないジョブであればこれでも構いませんが、多くのproductionでは永続的なバックエンドを選ぶ必要があります。

https://railsguides.jp/active_job_basics.html#%E3%82%B8%E3%83%A7%E3%83%96%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B

結局 sidekiq が必要でした。

**Comment by iwaseasahi** [comment]
sidekiq.yml についての説明。
https://github.com/mperham/sidekiq/wiki/Advanced-Options

**Comment by iwaseasahi** [comment]
https://blog.u6k.me/2018/04/29/sample-sidekiq.html

**Comment by iwaseasahi** [comment]
まずは https://www.christchurches-map.site/ で非同期処理が機能しているか調査します。

**Comment by iwaseasahi** [comment]
```
E, [2021-09-23T13:05:49.211443 #7] ERROR -- : Failed enqueuing ActionMailer::MailDeliveryJob to Sidekiq(mailers): ArgumentError (invalid uri scheme 'christchurches-map-ecs-redis.nagz8k.ng.0001.apne1.cache.amazonaws.com')
F, [2021-09-23T13:05:49.212895 #7] FATAL -- :
ArgumentError (invalid uri scheme 'christchurches-map-ecs-redis.nagz8k.ng.0001.apne1.cache.amazonaws.com'):

app/controllers/users/registrations_controller.rb:13:in `create'
```

**Comment by iwaseasahi** [comment]
環境変数 `REDIS` は 'redis://redis:6379' のように、先頭に `redis://` が必要です。
なぜなら、以下のコードで URI.parse をやっていますが、scheme が必要だからです。

https://github.com/iwaseasahi/christchurches-map/blob/98a4575a6d1be2132ba68b29453eb3d1fbf91699/config/initializers/redis.rb#L3

https://docs.ruby-lang.org/ja/latest/method/URI/s/parse.html

**Comment by iwaseasahi** [comment]
```
E, [2021-09-23T13:29:48.457676 #6] ERROR -- : Failed enqueuing ActionMailer::MailDeliveryJob to Sidekiq(mailers): Redis::ConnectionError (Connection lost (ECONNRESET))
F, [2021-09-23T13:29:48.459153 #6] FATAL -- :
Redis::ConnectionError (Connection lost (ECONNRESET)):

app/controllers/users/registrations_controller.rb:13:in `create'
```

**Comment by iwaseasahi** [comment]
```
E, [2021-09-23T13:41:39.483140 #9] ERROR -- : Failed enqueuing ActionMailer::MailDeliveryJob to Sidekiq(mailers): Redis::CannotConnectError (Error connecting to Redis on christchurches-map-ecs-redis-ro.nagz8k.ng.0001.apne1.cache.amazonaws.com:6379 (Redis::TimeoutError))
F, [2021-09-23T13:41:39.484818 #9] FATAL -- :
Redis::CannotConnectError (Error connecting to Redis on christchurches-map-ecs-redis-ro.nagz8k.ng.0001.apne1.cache.amazonaws.com:6379 (Redis::TimeoutError)):

app/controllers/users/registrations_controller.rb:13:in `create'
```

**Comment by iwaseasahi** [comment]
やっぱり sidekiq が起動していないからっぽいです。
https://stackoverflow.com/questions/57175267/how-to-fix-rediscannotconnecterror-error-connecting-to-redis-redistimeoute

**Comment by iwaseasahi** [comment]
> クラスターが利用可能な状態であり、クラスターへのアクセスを許可されている場合は、Amazon EC2 インスタンスにログインしてクラスターに接続できます。

https://docs.aws.amazon.com/ja_jp/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html

redis には、mac の local から接続できない？
EC2 を立ち上げて検証してみます。

**Comment by iwaseasahi** [comment]
EC2 を用意しました。
こちらに沿って redis-cli で接続します。
https://docs.aws.amazon.com/ja_jp/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html

**Comment by iwaseasahi** [comment]
セキュリティグループを開けて、EC2 から接続できました。

```
[ec2-user@ip redis-stable]$ src/redis-cli -h xxx.amazonaws.com -c -p 6379
xxx.amazonaws.com:6379>
```

**Comment by iwaseasahi** [comment]
まだ何も入っていませんでした。

```
xxx.amazonaws.com:6379> KEYS *
(empty array)
```

**Comment by iwaseasahi** [comment]
この issue と関係ないですが、AppSpec は以下です。

```
{
    "version": 1,
    "Resources": [
        {
            "TargetService": {
                "Type": "AWS::ECS::Service",
                "Properties": {
                    "TaskDefinition": "arn:aws:ecs:ap-northeast-1:xxxx:task-definition/christchurches-map-task:27",
                    "LoadBalancerInfo": {
                        "ContainerName": "christchurches-map-nginx",
                        "ContainerPort": 80
                    }
                }
            }
        }
    ]
}
```

**Comment by iwaseasahi** [comment]
ECS に deploy しましたが、redis に接続できませんでした。
https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#logsV2:log-groups/log-group/$252Fecs$252Fchristchurches-map-task/log-events/ecs$252Fchristchurches-map-sidekiq$252Fe34e79d1568b49a59b56cfb1e07aec27

**Comment by iwaseasahi** [comment]
環境変数 `REDIS` には以下の値を入れる必要がありました。

```
redis://christchurches-map-ecs-redis-001.nagz8k.0001.apne1.cache.amazonaws.com:6379
```

* `rediss://` ではダメ。
* host がプライマリーにする。

**Comment by iwaseasahi** [comment]
```
christchurches-map-ecs-redis-ro.nagz8k.ng.0001.apne1.cache.amazonaws.com:6379> KEYS *
1) "sidekiq:processes"
2) "sidekiq:stat:processed:2021-09-24"
3) "sidekiq:ip-10-0-0-215.ap-northeast-1.compute.internal:7:0014bbfc3419"
4) "sidekiq:stat:failed:2021-09-24"
5) "sidekiq:queues"
6) "sidekiq:stat:processed"
7) "sidekiq:stat:failed"
```

**Comment by iwaseasahi** [comment]
ちゃんとメール送信されました。
